- hosts: all
  tasks:
  - yum_repository:
        name: docker-ce
        description: "mydocker repo"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        gpgcheck: no
  - package: 
     name: "docker-ce-18.09.1-3.el7.x86_64"
     state: present
  - service:
     name: "docker"
     state: started
     enabled: yes
  - pip:
     name: docker
  - docker_image:
     name: httpd
     source: pull
  - file:
     path: /kaifi
     state: "directory"
  - copy:
     src: /var/www/html/asif.html
     dest: /var/www/html
  - docker_container:
     name: "myfirstweb"
     image: httpd
     state: started
     exposed_ports: "80"
     ports: 8080:80
     volumes: /var/www/html:/usr/local/apache2/htdocs
  - package:
     name: httpd
     state: present
  - service:
     name: httpd
     state: started
     enabled: yes



